[general]
import = [ "themes/vague.toml" ]

# [window]
# opacity = 0.95

[font]
normal = { family = "JetBrainsMono NF" }
size = 12.0

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
blink_timeout = 30

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullScreen" }
]
