--local rainbow_delimiters = require 'rainbow-delimiters'
--
--vim.api.nvim_set_hl(0, 'RainbowBracketYellow', { fg='#dad700' })
--vim.api.nvim_set_hl(0, 'RainbowBracketPink', { fg='#da70d6' })
--vim.api.nvim_set_hl(0, 'RainbowBracketBlue', { fg='#189fff' })
--
--vim.g.rainbow_delimiters = {
--  strategy = {
--    [''] = rainbow_delimiters.strategy['global'],
--  },
--  query = {
--    [''] = 'rainbow-delimiters',
--    lua = 'rainbow-blocks',
--  },
--  highlight = { },
--}
