CompileFlags:
  Add: [-Wall, -Wextra, -resource-dir=, -I/usr/include]
  Remove: [-resource-dir=]
  Compiler: gcc
---
InlayHints:
  Enabled: Yes
  BlockEnd: No
  Designators: No
  ParameterNames: Yes
  DeducedTypes: Yes
  TypeNameLimit: 24
---
If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Remove: [-std]
  Add: [-xc, -std=c11]
---
If:
  PathMatch: [.*\.cpp, .*\.hpp]
CompileFlags:
  Remove: [-std]
  Add: [-xc++, -std=c++17]
  Compiler: g++
